import { Post, Comment } from '@/types/post';

export const mockPosts: Post[] = [
  {
    id: 1,
    title: 'React 19의 새로운 기능들이 정식 출시되었습니다',
    content:
      'React 19가 정식으로 출시되었습니다. Server Components, Actions, 그리고 여러 새로운 훅들이 포함되어 있습니다. 이번 업데이트는 개발자 경험을 크게 향상시킬 것으로 기대됩니다.\n\nServer Components를 통해 서버에서 렌더링되는 컴포넌트를 만들 수 있게 되었고, 이는 성능 향상과 번들 크기 감소에 큰 도움이 됩니다. Actions는 폼 처리를 더욱 간편하게 만들어 줍니다.\n\n또한 새로운 use 훅과 useFormStatus, useFormState 등의 훅들이 추가되어 더욱 강력한 기능을 제공합니다.',
    author: '김개발',
    authorId: 'kim_dev',
    category: '공지사항',
    views: 1234,
    comments: 45,
    likes: 89,
    date: '2시간 전',
    isHot: true,
    tags: ['React', 'JavaScript', 'Web Development'],
  },
  {
    id: 2,
    title: 'TypeScript에서 Generic 타입 잘 사용하는 방법',
    content:
      'TypeScript의 Generic은 재사용 가능한 컴포넌트를 만들 때 매우 유용합니다. 이 글에서는 실전에서 자주 사용되는 Generic 패턴들을 소개합니다.\n\n1. 기본 Generic 함수\n2. Generic 인터페이스\n3. Generic 클래스\n4. Generic 제약 조건\n\n각 패턴별로 실제 사용 예시와 함께 설명하겠습니다.',
    author: '이타입',
    authorId: 'lee_type',
    category: 'Tips',
    views: 987,
    comments: 32,
    likes: 67,
    date: '5시간 전',
    isHot: true,
    tags: ['TypeScript', 'Programming'],
  },
  {
    id: 3,
    title: 'Next.js 15 App Router 마이그레이션 후기',
    content:
      'Pages Router에서 App Router로 마이그레이션한 경험을 공유합니다. 장점과 단점, 그리고 주의해야 할 점들을 정리했습니다.\n\nApp Router는 Server Components를 기본으로 사용하며, 레이아웃 시스템이 개선되었습니다. 하지만 기존 코드를 마이그레이션하는 과정에서 몇 가지 주의할 점이 있었습니다.',
    author: '박프론트',
    authorId: 'park_front',
    category: '정보',
    views: 856,
    comments: 28,
    likes: 54,
    date: '1일 전',
    isHot: false,
    tags: ['Next.js', 'React', 'Migration'],
  },
  {
    id: 4,
    title: 'CSS Grid vs Flexbox 언제 무엇을 써야 할까요?',
    content:
      'CSS 레이아웃을 구성할 때 Grid와 Flexbox 중 어떤 것을 선택해야 할지 고민이 되시나요? 각각의 사용 사례를 예제와 함께 설명합니다.\n\nFlexbox는 1차원 레이아웃에 적합하고, Grid는 2차원 레이아웃에 적합합니다. 하지만 실제로는 두 가지를 함께 사용하는 경우가 많습니다.',
    author: '최스타일',
    authorId: 'choi_style',
    category: '질문',
    views: 743,
    comments: 19,
    likes: 43,
    date: '1일 전',
    isHot: false,
    tags: ['CSS', 'Layout', 'Web Design'],
  },
  {
    id: 5,
    title: 'React Query로 서버 상태 관리하기',
    content:
      'React Query(TanStack Query)를 사용하면 서버 상태 관리가 매우 간편해집니다. 캐싱, 리페칭, 동기화 등의 기능을 자세히 알아봅니다.\n\n서버 상태와 클라이언트 상태를 분리하여 관리하면 코드가 더욱 깔끔해지고 유지보수가 쉬워집니다.',
    author: '정쿼리',
    authorId: 'jung_query',
    category: 'Tips',
    views: 621,
    comments: 15,
    likes: 38,
    date: '2일 전',
    isHot: false,
    tags: ['React Query', 'State Management'],
  },
  {
    id: 6,
    title: '웹 접근성 개선하기 - 실전 가이드',
    content:
      '웹 접근성은 모든 사용자가 웹사이트를 사용할 수 있도록 하는 중요한 요소입니다. ARIA 속성, 키보드 네비게이션 등을 알아봅니다.\n\n접근성을 고려한 웹 개발은 법적 요구사항일 뿐만 아니라 모든 사용자에게 더 나은 경험을 제공합니다.',
    author: '안웹앱',
    authorId: 'ahn_web',
    category: '정보',
    views: 534,
    comments: 12,
    likes: 29,
    date: '3일 전',
    isHot: false,
    tags: ['Accessibility', 'Web Standards'],
  },
  {
    id: 7,
    title: 'Vite vs Webpack 2024년 번들러 비교',
    content:
      '최근 많은 프로젝트가 Webpack에서 Vite로 전환하고 있습니다. 두 번들러의 차이점과 각각의 장단점을 비교 분석합니다.\n\nVite는 개발 서버 시작 속도가 빠르고 HMR이 거의 즉시 일어나는 반면, Webpack은 플러그인 생태계가 더 풍부합니다.',
    author: '강빌드',
    authorId: 'kang_build',
    category: '정보',
    views: 489,
    comments: 23,
    likes: 31,
    date: '4일 전',
    isHot: false,
    tags: ['Vite', 'Webpack', 'Build Tools'],
  },
  {
    id: 8,
    title: '프론트엔드 개발자 로드맵 2024',
    content:
      '2024년 프론트엔드 개발자가 되기 위해 학습해야 할 기술 스택과 로드맵을 정리했습니다. 초보자부터 중급자까지 참고하세요.\n\nHTML, CSS, JavaScript 기본부터 시작해서 React, TypeScript, 그리고 다양한 도구들을 단계별로 학습하는 것을 추천합니다.',
    author: '윤커리어',
    authorId: 'yoon_career',
    category: '자유',
    views: 412,
    comments: 18,
    likes: 26,
    date: '5일 전',
    isHot: false,
    tags: ['Career', 'Learning', 'Frontend'],
  },
  {
    id: 9,
    title: 'Next.js에서 이미지 최적화 완벽 가이드',
    content:
      'Next.js의 Image 컴포넌트를 사용한 이미지 최적화 방법을 소개합니다. lazy loading, responsive images, blur placeholder 등 다양한 기능을 활용해보세요.',
    author: '김개발',
    authorId: 'kim_dev',
    category: 'Tips',
    views: 678,
    comments: 21,
    likes: 45,
    date: '6일 전',
    isHot: false,
    tags: ['Next.js', 'Performance', 'Images'],
  },
  {
    id: 10,
    title: 'Tailwind CSS 커스터마이징 팁 모음',
    content:
      'Tailwind CSS를 프로젝트에 맞게 커스터마이징하는 다양한 방법들을 소개합니다. 테마 설정, 플러그인 사용, 커스텀 유틸리티 클래스 만들기 등을 다룹니다.',
    author: '최스타일',
    authorId: 'choi_style',
    category: 'Tips',
    views: 523,
    comments: 14,
    likes: 32,
    date: '1주일 전',
    isHot: false,
    tags: ['Tailwind CSS', 'Styling', 'CSS'],
  },
];

export const mockComments: Comment[] = [
  {
    id: 1,
    postId: 1,
    author: '이댓글',
    content: '좋은 정보 감사합니다! React 19 정말 기대되네요.',
    date: '1시간 전',
    likes: 5,
  },
  {
    id: 2,
    postId: 1,
    author: '박반응',
    content: 'Server Components가 정말 게임체인저가 될 것 같습니다.',
    date: '30분 전',
    likes: 3,
  },
  {
    id: 3,
    postId: 2,
    author: '정제네릭',
    content: 'Generic 사용하는데 항상 헷갈렸는데 도움이 많이 되었습니다.',
    date: '3시간 전',
    likes: 7,
  },
];
